In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv(r'C:\Users\KN\Desktop\MusicRecommendationSystem\SpotifyAudioFeaturesNov2018.csv')


In [3]:
dataset

artist_name                track_id  \
0                    YG  2RM4jf1Xa9zPgMGRDiht8O   
1                    YG  1tHDG53xJNGsItRA3vfVgs   
2                 R3HAB  6Wosx2euFPMT14UXiWudMy   
3            Chris Cooq  3J2Jpw61sO7l6Hc7qdYV91   
4            Chris Cooq  2jbYvQCyPgX3CdmAzeVeuS   
...                 ...                     ...   
116367  Roma Atmosphere  5R9ukMX7BDIy1WJYsAhBD6   
116368     Philthy Rich  6LlTJUQPhqvZuvOmgkLGYh   
116369  Nef The Pharaoh  0B2LhMYcGR9Gmi6BQLdzlO   
116370   The Ting Tings  0yzA9b21pJgnlLQDirsxAm   
116371        mingi pak  2ud0K7X5LzmxJP2LEvkHio   

                                            track_name  acousticness  \
0       Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj      0.005820   
1                         BAND DRUM (feat. A$AP Rocky)      0.024400   
2                                        Radio Silence      0.025000   
3                                              Lactose      0.029400   
4                                  Same - Original mix      0.000035   
...                                                ...           ...   
116367                                      Sette Oche      0.978000   
116368    Off Safety (feat. Yhung T.O., Mozzy & Ziggy)      0.099200   
116369                                        Ludacris      0.027700   
116370                                       Estranged      0.067500   
116371                                          clouds      0.472000   

        danceability  duration_ms  energy  instrumentalness  key  liveness  \
0              0.743       238373   0.339            0.0000    1    0.0812   
1              0.846       214800   0.557            0.0000    8    0.2860   
2              0.603       138913   0.723            0.0000    9    0.0824   
3              0.800       125381   0.579            0.9120    5    0.0994   
4              0.783       124016   0.792            0.8780    7    0.0332   
...              ...          ...     ...               ...  ...       ...   
116367         0.103       245714   0.086            0.9630    9    0.0987   
116368         0.674       221934   0.628            0.0000    9    0.3740   
116369         0.792       183771   0.747            0.0000   11    0.1170   
116370         0.548       311267   0.506            0.0244   10    0.1050   
116371         0.785       106500   0.145            0.9400   11    0.0998   

        loudness  mode  speechiness    tempo  time_signature  valence  \
0         -7.678     1       0.4090  203.927               4    0.118   
1         -7.259     1       0.4570  159.009               4    0.371   
2         -5.890     0       0.0454  114.966               4    0.382   
3        -12.118     0       0.0701  123.003               4    0.641   
4        -10.277     1       0.0661  120.047               4    0.928   
...          ...   ...          ...      ...             ...      ...   
116367   -20.715     0       0.0399   57.545               4    0.037   
116368    -8.277     0       0.1890   93.053               4    0.613   
116369    -8.753     0       0.3420   94.498               4    0.584   
116370    -8.251     1       0.0286  163.967               4    0.271   
116371    -9.474     1       0.2200  142.091               4    0.433   

        popularity  
0               44  
1               10  
2               63  
3                9  
4                8  
...            ...  
116367          55  
116368          46  
116369          47  
116370          50  
116371          52  

[116372 rows x 17 columns]

In [4]:
from sklearn import metrics


In [5]:
from sklearn.cluster import KMeans
X = dataset.iloc[:,[-1]].values
x_train,x_test=train_test_split(X,test_size=0.33,random_state=0)
kmeans = KMeans(n_clusters = 7, init = 'k-means++', random_state = 2)
y_kmeans = kmeans.fit_predict(x_test)

In [6]:
from sklearn.metrics import confusion_matrix,classification_report
print("ConfusionMatrix:\n",confusion_matrix(y_kmeans,kmeans.labels_))
print(classification_report(y_kmeans,kmeans.labels_))

ConfusionMatrix:
 [[7322    0    0    0    0    0    0]
 [   0 3885    0    0    0    0    0]
 [   0    0 7334    0    0    0    0]
 [   0    0    0 7297    0    0    0]
 [   0    0    0    0 1642    0    0]
 [   0    0    0    0    0 4557    0]
 [   0    0    0    0    0    0 6366]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7322
           1       1.00      1.00      1.00      3885
           2       1.00      1.00      1.00      7334
           3       1.00      1.00      1.00      7297
           4       1.00      1.00      1.00      1642
           5       1.00      1.00      1.00      4557
           6       1.00      1.00      1.00      6366

    accuracy                           1.00     38403
   macro avg       1.00      1.00      1.00     38403
weighted avg       1.00      1.00      1.00     38403



In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(y_kmeans, kmeans.labels_)

1.0